# Generated by Django 3.1.5 on 2021-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Shark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.ManyToManyField(related_name='shark_human', to='shark.Human', verbose_name='человек')),
            ],
            options={
                'verbose_name': 'Акула',
                'verbose_name_plural': 'Акулы',
            },
        ),
    ]
